### PR TITLE
Add missing elm-platform

### PR DESCRIPTION
**Pull request by samccone**

### CODE REVIEW

**Comment by evancz** [comment]
This library is very deprecated!

**Comment by evancz** [comment]
`Signal.Mailbox` and `Signal.forwardTo` fill the role that this used to.

**Comment by samccone** [comment]
Great thanks for the info, would you accept a PR marking this libs readme as deprecated and redirecting users to these other projects?

**Comment by evancz** [comment]
I just did an update of package.elm-lang.org and it is not filtering out "old stuff" from the results right now. Once that's added, this should be hidden from people. So it should be fixed through other means!

**Pull request closed without merging**
